/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;

import conexion.BaseDatos;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author davidpulloquinga
 */
public class Ciudad_WinEDT extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ciudad_Win
     */
       String bandera, imagen=null;
    String rutacity,ruta,nombre;
    public Ciudad_WinEDT() {
        initComponents();
        txt_descripcion.setEnabled(false);
        txt_poblacion.setEnabled(false);
        asignar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pic_bandera = new javax.swing.JLabel();
        pic_ciudad = new javax.swing.JLabel();
        txt_poblacion = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        btn_carbar_flag = new javax.swing.JButton();
        btn_cargar_city = new javax.swing.JButton();
        btn_ingresar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb_nombre = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 46, -1, -1));

        jLabel2.setText("Descripcion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setText("Poblacion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        pic_bandera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic_bandera.setBorder(javax.swing.BorderFactory.createTitledBorder("Bandera"));
        getContentPane().add(pic_bandera, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 160, 150));

        pic_ciudad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic_ciudad.setBorder(javax.swing.BorderFactory.createTitledBorder("Ciudad"));
        getContentPane().add(pic_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 170, 170));
        getContentPane().add(txt_poblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, -1));
        getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 160, -1));

        btn_carbar_flag.setText("Cargar");
        btn_carbar_flag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carbar_flagActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carbar_flag, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        btn_cargar_city.setText("Cargar");
        btn_cargar_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargar_cityActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cargar_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        btn_cancelar.setText("Cancelar");
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        jLabel6.setText("Formulario de ingreso de Ciudades");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        cb_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_nombreMouseClicked(evt);
            }
        });
        getContentPane().add(cb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 160, -1));

        jButton1.setText("Cargar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_carbar_flagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carbar_flagActionPerformed
        // TODO add your handling code here:
            final JFileChooser elegirImagen = new JFileChooser();
        elegirImagen.setMultiSelectionEnabled(false);
        int o = elegirImagen.showOpenDialog(this);
        if(o == JFileChooser.APPROVE_OPTION){
                ruta = elegirImagen.getSelectedFile().getAbsolutePath();
                String nombre = elegirImagen.getSelectedFile().getName();
            System.out.println(ruta);
            Image preview = Toolkit.getDefaultToolkit().getImage(ruta);
            if(preview != null){
                pic_bandera.setText("");
                ImageIcon icon = new ImageIcon(preview.getScaledInstance(pic_bandera.getWidth(), pic_bandera.getHeight(), Image.SCALE_DEFAULT));
                pic_bandera.setIcon(icon);
            }
        }
    }//GEN-LAST:event_btn_carbar_flagActionPerformed

    private void btn_cargar_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargar_cityActionPerformed
        // TODO add your handling code here:
          final JFileChooser elegirImagen = new JFileChooser();
        elegirImagen.setMultiSelectionEnabled(false);
        int o = elegirImagen.showOpenDialog(this);
        if(o == JFileChooser.APPROVE_OPTION){
                rutacity = elegirImagen.getSelectedFile().getAbsolutePath();
                String nombre = elegirImagen.getSelectedFile().getName();
            System.out.println(rutacity);
            Image preview = Toolkit.getDefaultToolkit().getImage(rutacity);
            if(preview != null){
                pic_ciudad.setText("");
                ImageIcon icon = new ImageIcon(preview.getScaledInstance(pic_ciudad.getWidth(), pic_ciudad.getHeight(), Image.SCALE_DEFAULT));
                pic_ciudad.setIcon(icon);
            }
        }
    }//GEN-LAST:event_btn_cargar_cityActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void cb_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_nombreMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_nombreMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//         TODO add your handling code here:
     
        BaseDatos bd = new BaseDatos();
        LinkedList lista;
        lista = new LinkedList();
        lista =  bd.ObtenerCiudad_datos(cb_nombre.getSelectedItem().toString());
   
            txt_descripcion.setText(lista.get(1).toString());
            txt_poblacion.setText(lista.get(2).toString());
            bandera= lista.get(3).toString();
            imagen = lista.get(4).toString();
        System.out.println(bandera+"Bandera");
            System.out.println(imagen+"Ciudad");
        cargarFotoCiudad();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_carbar_flag;
    private javax.swing.JButton btn_cargar_city;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JComboBox cb_nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel pic_bandera;
    private javax.swing.JLabel pic_ciudad;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_poblacion;
    // End of variables declaration//GEN-END:variables

public  void asignar(){
    LinkedList lista = new LinkedList();
   
    BaseDatos bd = new BaseDatos();
    lista= bd.ObtenerCiudad_nombre();
    DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Object lista1 : lista) {
            model.addElement(lista1);
        }
        cb_nombre.setModel(model);
}
public void cargarFotoCiudad(){
if (imagen.startsWith("/")) {
                    Image preview = Toolkit.getDefaultToolkit().getImage(imagen);
                    if (preview != null) {
                        pic_ciudad.setText("");
                        ImageIcon icon = new ImageIcon(preview.getScaledInstance(pic_ciudad.getWidth(), pic_ciudad.getHeight(), Image.SCALE_DEFAULT));
                        pic_ciudad.setIcon(icon);
                    }
                    else
                    {
                        System.out.println("Error");
                    }
                       
                } else {
                    String ruta2 = "/Users/davidpulloquinga/Documents/Proyectos/Integrador/Integrador/" + imagen;
                    System.out.println(ruta2+"esta por este lado");
                     Image preview = Toolkit.getDefaultToolkit().getImage(ruta2);
                    if (preview != null) {
                        pic_ciudad.setText("");
                        ImageIcon icon = new ImageIcon(preview.getScaledInstance(pic_ciudad.getWidth(), pic_ciudad.getHeight(), Image.SCALE_DEFAULT));
                        pic_ciudad.setIcon(icon);
                    }
                }


}
}

