/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;

import conexion.BaseDatos;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import logic.ValidacionCedula;


/**
 *
 * @author davidpulloquinga
 */
public class Guias_WinEDT extends javax.swing.JInternalFrame implements Runnable{

    /**
     * Creates new form Guias_Win
     */
    private static final String HOST="localhost";
    private static final String USER="root";
    private static final String PASS="";
    String ruta,nombre;
    public Guias_WinEDT() {
        initComponents();
        txt_nombre.setEnabled(false);
        txt_about.setEnabled(false);
        txt_antiguedad.setEnabled(false);
        txt_apellido.setEnabled(false);
        txt_telefono.setEnabled(false);
        txt_email.setEnabled(false);
        cb_genero.setEnabled(false);
        txt_born.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        cb_genero = new javax.swing.JComboBox();
        txt_cedula = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_about = new javax.swing.JTextArea();
        foto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_antiguedad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_born = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Avenida de los Volcanes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha/Nacimiento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cédula:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Género:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Antiguedad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Teléfono:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Foto");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descripción:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, -1));
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 160, -1));

        cb_genero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        getContentPane().add(cb_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 140, -1));

        txt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 160, -1));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 170, -1));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 160, -1));

        txt_about.setColumns(20);
        txt_about.setLineWrap(true);
        txt_about.setRows(5);
        jScrollPane1.setViewportView(txt_about);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        foto.setForeground(new java.awt.Color(255, 255, 255));
        foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto.setMaximumSize(new java.awt.Dimension(75, 75));
        foto.setMinimumSize(new java.awt.Dimension(75, 75));
        foto.setPreferredSize(new java.awt.Dimension(75, 75));
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 130, 120));

        jButton1.setText("Subir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));
        getContentPane().add(txt_antiguedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 140, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Formulario de Edición de Guias");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        jButton3.setText("Cancelar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));
        getContentPane().add(txt_born, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 100, -1));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graficas/panamericana_cotopaxi.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 450, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ValidacionCedula validacion = new ValidacionCedula();
        if (validacion.validadorDeCedula(txt_cedula.getText())) {
            run();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cédula incorrecta, ingrese de nuevo");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        final JFileChooser elegirImagen = new JFileChooser();
        elegirImagen.setMultiSelectionEnabled(false);
        int o = elegirImagen.showOpenDialog(this);
        if (o == JFileChooser.APPROVE_OPTION) {
            ruta = elegirImagen.getSelectedFile().getAbsolutePath();
            nombre = elegirImagen.getSelectedFile().getName();
            Image preview = Toolkit.getDefaultToolkit().getImage(ruta);
            if (preview != null) {
                foto.setText("");
                ImageIcon icon = new ImageIcon(preview.getScaledInstance(foto.getWidth(), foto.getHeight(), Image.SCALE_DEFAULT));
                foto.setIcon(icon);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_cedulaKeyTyped

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
            // TODO add your handling code here:
        run();
        
    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox cb_genero;
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_about;
    private javax.swing.JTextField txt_antiguedad;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_born;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        String [] split = null;
        BaseDatos bd = new BaseDatos(HOST,USER, PASS);
        String dato;
        ValidacionCedula validar = new ValidacionCedula();
        if (validar.validadorDeCedula(txt_cedula.getText())) {
            if (bd.searchGuia(txt_cedula.getText())) {
                JOptionPane.showMessageDialog(rootPane,
                        "Guia Encontrado se procedera a cargar los datos");
                txt_nombre.setEnabled(true);
                txt_about.setEnabled(true);
                txt_antiguedad.setEnabled(true);
                txt_apellido.setEnabled(true);
                txt_telefono.setEnabled(true);
                txt_email.setEnabled(true);
                cb_genero.setEnabled(true);
                txt_born.setEnabled(true);
                dato=bd.fillGuia(txt_cedula.getText());
                split = dato.split("\\?");
                txt_nombre.setText(split[0]);
                txt_apellido.setText(split[1]);
                txt_born.setText(split[2]);
                txt_antiguedad.setText(split[5]);
                txt_email.setText(split[6]);
                txt_telefono.setText(split[7]);
                txt_about.setText(split[9]);
                if ("Masculino".equals(split[4])) {
                   cb_genero.setSelectedIndex(0);
                }
                else
                {
                    cb_genero.setSelectedIndex(1);
                }
            } else
                JOptionPane.showMessageDialog(rootPane, "No se ha encotrado"
                        + " ningun guia con la cedula ingresada");
        }
        else
            JOptionPane.showMessageDialog(rootPane,"Cedula ingrada incorrecta");
    }
   
}