/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;

import conexion.BaseDatos;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author davidpulloquinga
 */
public class Hospedajes_WinEDT extends javax.swing.JInternalFrame {

    /**
     * Creates new form Hospedajes_Win
     */
    
    String ruta;
    public Hospedajes_WinEDT() {
        
        initComponents();
        asignar();
        txt_about.setEnabled(false);
        txt_costo.setEnabled(false);
        txt_direccion.setEnabled(false);
        txt_telefono.setEnabled(false);
        btn_cargar.setEnabled(false);
        btn_actualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        galerias_WinEDT1 = new ventanas.Galerias_WinEDT();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_about = new javax.swing.JTextArea();
        txt_costo = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        pic_imagen = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        btn_cargar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JComboBox();
        btn_consultar = new javax.swing.JButton();

        galerias_WinEDT1.setVisible(true);

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Formulario para ingreso de Hospedajes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, -1));

        jLabel3.setText("Descripción:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel4.setText("Costo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        txt_about.setColumns(20);
        txt_about.setRows(5);
        jScrollPane1.setViewportView(txt_about);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 250, -1));
        getContentPane().add(txt_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, -1));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 200, -1));
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 250, -1));

        pic_imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic_imagen.setText("Foto");
        pic_imagen.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen"));
        getContentPane().add(pic_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 150, 160));

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        btn_cargar.setText("Cargar");
        btn_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 210, -1));

        btn_consultar.setText("Cargar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarActionPerformed
        // TODO add your handling code here:
        final JFileChooser elegirImagen = new JFileChooser();
        elegirImagen.setMultiSelectionEnabled(false);
        int o = elegirImagen.showOpenDialog(this);
        if(o == JFileChooser.APPROVE_OPTION){
                ruta = elegirImagen.getSelectedFile().getAbsolutePath();
                String nombre = elegirImagen.getSelectedFile().getName();
            System.out.println(ruta);
            Image preview = Toolkit.getDefaultToolkit().getImage(ruta);
            if(preview != null){
                pic_imagen.setText("");
                ImageIcon icon = new ImageIcon(preview.getScaledInstance(pic_imagen.getWidth(), pic_imagen.getHeight(), Image.SCALE_DEFAULT));
                pic_imagen.setIcon(icon);
            }
        }
    }//GEN-LAST:event_btn_cargarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
      BaseDatos bd = new BaseDatos();
      if (bd.updateHospedajes(txt_nombre.getSelectedItem().toString(), txt_about.getText(), Integer.parseInt(txt_costo.getText()),txt_telefono.getText(),txt_direccion.getText(), ruta)) {
        JOptionPane.showMessageDialog(rootPane,"Hospedaje actualizado correctamente");
        txt_about.setText(null);
        txt_costo.setText(null);
        txt_direccion.setText(null);
        txt_telefono.setText(null);
        pic_imagen.setIcon(null);
        txt_about.setEnabled(false);
        txt_costo.setEnabled(false);
        txt_direccion.setEnabled(false);
        txt_telefono.setEnabled(false);
        btn_cargar.setEnabled(false);
        btn_actualizar.setEnabled(false);
        
      }
        else
            JOptionPane.showMessageDialog(rootPane,"Ha ocurrido un error");
      
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        // TODO add your handling code here:
        BaseDatos baseDatos = new BaseDatos();
         LinkedList lista;
        lista = new LinkedList();
       lista =  baseDatos.ObtenerHospedaje_datos(txt_nombre.getSelectedItem().toString());
        if (lista!=null) {
            txt_about.setText(lista.get(0).toString());
            txt_costo.setText(lista.get(1).toString());
            txt_telefono.setText(lista.get(2).toString());
            txt_direccion.setText(lista.get(3).toString());
            ruta = lista.get(4).toString();
            cargarImagen(ruta);
            txt_about.setEnabled(true);
        txt_costo.setEnabled(true);
        txt_direccion.setEnabled(true);
        txt_telefono.setEnabled(true);
        btn_cargar.setEnabled(true);
        btn_actualizar.setEnabled(true);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Existe un error");

    }//GEN-LAST:event_btn_consultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_cargar;
    private javax.swing.JButton btn_consultar;
    private ventanas.Galerias_WinEDT galerias_WinEDT1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pic_imagen;
    private javax.swing.JTextArea txt_about;
    private javax.swing.JTextField txt_costo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JComboBox txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
public final  void asignar(){
    LinkedList lista = new LinkedList();
   
    BaseDatos bd = new BaseDatos();
        lista = bd.obtenerNombreHospedajes();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Object lista1 : lista) {
            model.addElement(lista1);
        }
        txt_nombre.setModel(model);
    }
public void cargarImagen(String imagen){
        if (imagen.startsWith("/")) {
            Image preview = Toolkit.getDefaultToolkit().getImage(imagen);
            if (preview != null) {
                pic_imagen.setText("");
                ImageIcon icon = new ImageIcon(preview.getScaledInstance(pic_imagen.getWidth(), pic_imagen.getHeight(), Image.SCALE_DEFAULT));
                pic_imagen.setIcon(icon);
                btn_cargar.setEnabled(true);
            } else {
                System.out.println("Error");
            }

        } else {
            String rutados = "/Users/davidpulloquinga/Documents/Proyectos/Integrador/Integrador/" + imagen;
            System.out.println(rutados + "esta por este lado");
            Image preview = Toolkit.getDefaultToolkit().getImage(rutados);
            if (preview != null) {
                pic_imagen.setText("");
                ImageIcon icon = new ImageIcon(preview.getScaledInstance(pic_imagen.getWidth(), pic_imagen.getHeight(), Image.SCALE_DEFAULT));
                pic_imagen.setIcon(icon);
                btn_cargar.setEnabled(true);
            }
        }
    
    }

}



