/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;

import conexion.BaseDatos;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author davidpulloquinga
 */
public class Usuarios_WinEDT extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuarios_Win
     */
    
    public Usuarios_WinEDT() {
        initComponents();
       asignar();
       txt_apellido.setEnabled(false);
       txt_email.setEnabled(false);
       txt_nombre.setEnabled(false);
       txt_pass.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_nick = new javax.swing.JComboBox();
        btn_cargar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Formulario para ingreso de usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 6, -1, -1));

        jLabel2.setText("Nickname:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 46, -1, -1));

        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 92, -1, -1));

        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 138, -1, -1));

        jLabel5.setText("Apellido:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 228, -1, -1));

        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 182, -1, -1));
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 86, 161, -1));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 132, 161, -1));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 176, 161, -1));
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 222, 161, -1));

        btn_agregar.setText("Actualizar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        txt_nick.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        getContentPane().add(txt_nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 160, -1));

        btn_cargar.setText("Cargar");
        btn_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
         BaseDatos bd = new  BaseDatos();
         if (bd.updateUsuarios(txt_nick.getSelectedItem().toString(), txt_pass.getText(), txt_email.getText(), txt_nombre.getText(), txt_apellido.getText())) {
            JOptionPane.showMessageDialog(rootPane,"Actualizacion exitosa");
            txt_apellido.setText(null);
            txt_email.setText(null);
            txt_nombre.setText(null);
            txt_pass.setText(null);
            txt_nick.setSelectedIndex(0);
            txt_apellido.setEnabled(false);
       txt_email.setEnabled(false);
       txt_nombre.setEnabled(false);
       txt_pass.setEnabled(false);
        }
        
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarActionPerformed
        // TODO add your handling code here:
        BaseDatos bd = new BaseDatos();
        LinkedList lista;
        lista = new LinkedList();
        lista =  bd.ObtenerUsuarios_datos(txt_nick.getSelectedItem().toString());
        if (lista!=null) {
            txt_pass.setText(lista.get(0).toString());
            txt_email.setText(lista.get(1).toString());
            txt_nombre.setText(lista.get(2).toString());
            txt_apellido.setText(lista.get(3).toString());
            
            txt_apellido.setEnabled(true);
       txt_email.setEnabled(true);
       txt_nombre.setEnabled(true);
       txt_pass.setEnabled(true);
          
        }
    }//GEN-LAST:event_btn_cargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_email;
    private javax.swing.JComboBox txt_nick;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_pass;
    // End of variables declaration//GEN-END:variables

public final  void asignar(){
    LinkedList lista = new LinkedList();
   
    BaseDatos bd = new BaseDatos();
        lista = bd.obtenerNombreNick();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Object lista1 : lista) {
            model.addElement(lista1);
        }
        txt_nick.setModel(model);
    }


}
